# Generated by Django 3.2 on 2021-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoty',
            name='total_time',
            field=models.IntegerField(default=3),
        ),
    ]
