# Generated by Django 3.2 on 2021-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0002_categoty_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoty',
            name='photo',
            field=models.ImageField(default='product1.jpg', upload_to='categoy images/'),
        ),
    ]
