# Generated by Django 3.2 on 2021-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0003_categoty_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hints',
            field=models.TextField(default="this is hint's of this answer"),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=20),
        ),
    ]
