# Generated by Django 3.2 on 2021-06-11 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Quiz', '0004_auto_20210608_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoty',
            name='attemp',
            field=models.ManyToManyField(blank=True, null=True, related_name='attemp', to=settings.AUTH_USER_MODEL),
        ),
    ]
