# Generated by Django 3.2 on 2021-06-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0008_tempresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempresult',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Quiz.categoty'),
        ),
    ]
