# Generated by Django 3.2 on 2021-06-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0010_alter_tempresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempresult',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
