# Generated by Django 3.2 on 2021-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0011_tempresult_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempresult',
            name='asnwer_show',
            field=models.IntegerField(default=0),
        ),
    ]
