# Generated by Django 3.2 on 2021-06-14 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Quiz', '0014_remove_tempresult_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='read_at',
            field=models.ManyToManyField(blank=True, related_name='read_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
