# Generated by Django 3.2 on 2021-06-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0015_question_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoty',
            name='attemp1_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoty',
            name='attemp2_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoty',
            name='attemp3_s',
            field=models.IntegerField(default=0),
        ),
    ]
