# Generated by Django 3.2 on 2021-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0017_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(default='product1.jpg', upload_to='Tournaments'),
        ),
    ]
