# Generated by Django 3.2 on 2021-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0018_tournament_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='time',
            field=models.IntegerField(default=2),
        ),
    ]
