# Generated by Django 3.2 on 2021-07-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0019_tournament_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=150)),
                ('option2', models.CharField(max_length=150)),
                ('option3', models.CharField(max_length=150)),
                ('option4', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Quiz.tournament')),
            ],
        ),
    ]
