# Generated by Django 3.2.5 on 2021-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0024_remove_quizatemp_attemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizatemp',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizatemp',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
