# Generated by Django 3.2 on 2021-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0026_auto_20210805_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fisrt_attemp',
            field=models.BooleanField(default=False),
        ),
    ]
