# Generated by Django 3.2 on 2021-08-10 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Quiz', '0027_tournament_fisrt_attemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='fisrt_attemp',
        ),
        migrations.AddField(
            model_name='tournament',
            name='fisrt_attemp',
            field=models.ManyToManyField(blank=True, related_name='first_attemp', to=settings.AUTH_USER_MODEL),
        ),
    ]
